name: Playwright Test Batch

on:
  schedule:
    - cron: "0 3,15 * * *"
  workflow_dispatch:

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm install
          npx playwright install --with-deps

      - name: Run Playwright tests and save report
        run: |
          npx playwright test --reporter=json > result.json

      - name: Parse failed tests
        run: python scripts/parse_failures.py

      - name: Create Jira issues (if failures exist)
        run: python scripts/create_jira.py
        env:
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_URL: ${{ secrets.JIRA_URL }}

      - name: Send Slack notification
        run: python scripts/send_slack.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
