name: Run QA Tests and Send Report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *"  # 하루 2회 (UTC 기준, KST 오전 9시/오후 9시)

jobs:
  qa-test:
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install -r ../requirements.txt

      - name: Set up Node.js (for Playwright)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright and dependencies
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run Playwright tests and generate result.json
        run: |
          npx playwright test --reporter=json > ../result.json

      - name: Parse test results → summary.json
        run: python parse_results.py

      - name: Register Jira issues
        run: python create_jira.py
        env:
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_URL: ${{ secrets.JIRA_URL }}

      - name: Send Slack notification
        run: python send_slack.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
