name: BAY QA Tests

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0,12 * * *"  # 하루 2회 (UTC 기준, KST 오전 9시/오후 9시)

jobs:
  qa-test:
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      
      - name: Run Playwright tests and generate result.json
        run: |
          python scripts/run_tests_and_generate_json.py

      - name: Register Jira issues
        run: python scripts/create_jira.py
        env:
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_PROJECTKEY : ${{ secrets.JIRA_PROJECTKEY}}

      - name: Send Slack notification
        run: python scripts/send_slack.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          JIRA_URL: ${{ secrets.JIRA_URL }}


